### ISSUE TITLE
Implement backend authentication system

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#105]
Now that Google+ signon is implemented in the frontend, we need to validate security tokens on every request that should be secured.  

Each secured API call should accept a query string parameter security_token which is a Google+ access token.  This token should be validated each request to ensure the validity of the request.  This should NOT check roles.

**Comment by sichinumi** [comment]
Implemented on my repo - has not been pulled to dev, as Will/Enzo need to integrate it with frontend.
