### ISSUE TITLE
Maplist Activate button triggers delete action after delete has been performed

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#106]
Repro steps:  
1.  Delete top maplist in maplist screen
2.  Attempt to activate other maplist further down in the list
3.  Note that delete dialog appears.

**Comment by wbbarr** [comment]
It appears this also occurs with activate as well.

**Comment by EnzoMartin** [comment]
Which branch are you in? It's working fine for me in dev-unstable

**Comment by wbbarr** [comment]
It seems to be doing it on the dev site, so, and I'm pretty sure that's on latest from dev-unstable.

**Comment by EnzoMartin** [comment]
dev-unstable is in sync with my develop branch, which doesn't have the bug as far as I've been able to test

**Comment by wbbarr** [comment]
Ok, I'll close this as no-repro.  I forced it to update on the dev site, and it looks like the failing chutzpah test caused the updates not to go live.
