### ISSUE TITLE
Squad messages no longer being received properly

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#108]
I've just verified in procon that the latest version of GSWAT (the one deployed to the dev server) does not receive any squad messages.  Only global, server, and team chat messages.  I'm not exactly sure why right now, but if they're being recorded, they're not making it to the live chat display.

**Comment by wbbarr** [comment]
So it looks like the squad names are messed up now, but they're making it to the log file:  

[3/14/2013 12:19:13 AM] [ALPHA1] IronDoq:  ty
[3/14/2013 12:19:04 AM] [ALPHA1] IronDoq:  wait
[3/14/2013 12:12:11 AM] [ALPHA7] GrinningMouth38:  i am on TS audio
[3/14/2013 12:03:24 AM] [BRAVO7] GrinningMouth38:  perks's's'ss

So I'm not sure what's up with those squad names.  They are in the text log, which indicates they're getting through the comm layer.  @EnzoMartin78, any ideas?

**Comment by EnzoMartin** [comment]
Squad messages are missing their team information, which is making them not get parsed. The JSON received from the server no longer contains their team with the squad name for some reason

**Comment by wbbarr** [comment]
Ok, referring back to @mamidon for further investigation.

**Comment by wbbarr** [comment]
I'll investigate this.

**Comment by wbbarr** [comment]
Blaming b830c266022c76a42111b9d1c7b5127fcbb579b3 -- the OnChat RCON class had some extra handling logic to split up the words from the message. I'll work on reimplementing this with the current changes to the CommLayer/Core.
