### ISSUE TITLE
!pageadmin not shown in chat logs

### ISSUE THREAD

**Issue by Smileynulk** [Pure-Battlefield/gswat#117]
Pulled 3/14/2013 & 3/15/2013 logs and players talking to server is not shown. e.g. cannot see when a player uses the !pageadmin command, can only see the server's response to player.  Also cannot see admin responses.
![03142013 pageadmin log](https://f.cloud.github.com/assets/3879962/266211/86d3ad16-8dd9-11e2-9a65-b54175831ece.jpg)

**Comment by wbbarr** [comment]
Resolved as no repro.
