### ISSUE TITLE
Menu cutting off the border when GSWAT is in half screen

### ISSUE THREAD

**Issue by Smileynulk** [Pure-Battlefield/gswat#121]
Chrome on Win7 Pro

![GSWAT Halfscreen Menu](https://f.cloud.github.com/assets/3879962/267247/409f5c8c-8e6f-11e2-859d-ee4469ad04dd.jpg)

**Comment by wbbarr** [comment]
I've also noticed the same thing occurs on WP8 as well (looks like it's just a size-related issue).

**Comment by EnzoMartin** [comment]
It's a slight difference between bootstrap 2 and 3's top height, I'll fix it this weekend

**Comment by wbbarr** [comment]
Resolved as of current dev build.
