### ISSUE TITLE
CommLayer failure on subsequent server connections

### ISSUE THREAD

**Issue by sichinumi** [Pure-Battlefield/gswat#14]
Currently, an exception is thrown when an attempt is made to connect to a server after the initial connection. (The first connection registers fine, but the second and subsequent connections fail.)

Debug notes: Set a breakpoint on RconProtocol.Connect() in CommLayer's Connect() function. On the second and subsequent calls, RconProtocol.Connect() will fail.

**Comment by mamidon** [comment]
Investigating -- the code 'should' account for this, so the issue is not immediately clear.

**Comment by sichinumi** [comment]
Resolved as of commit 58b78872daeb8a1688ab7060cb12aa79880ed2a3
