### ISSUE TITLE
Chat logs are not loaded on mobile browsers after selecting a date

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#24]
The JS update code is not working; the client still receives live updates instead of seeing the older chat logs.  

Most likely related to jquery vs jquery mobile being used.

**Comment by connerdavis47** [comment]
Potential fix will be committed soon, but this will take lots of painful testing over and over again if this first fix isn't actually a fix.  If that makes sense.  Maybe we'll get lucky.

**Comment by wbbarr** [comment]
I get a feeling that this is going to be resolved with https://github.com/Pure-Battlefield/gswat/issues/43, but Enzo will need to weigh in on this.

**Comment by EnzoMartin** [comment]
Assign over to me and I'll make sure to check it before doing a pull request

**Comment by wbbarr** [comment]
Resolved as of a while ago.  Got fixed with the frontend redo.
