### ISSUE TITLE
Add loading animation when loading chat logs

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#28]
As I just discovered from trying to load the chat logs from 12/31/2012, the load time can be several seconds long.  We should have some kind of spinner or other loading animation to show the user that we're actually loading the data.

**Comment by connerdavis47** [comment]
I made it so a message should appear whenever the chat is loading, but I guess that's not rendering.  I'll be gone all day so I'll get back to it later.

**Comment by wbbarr** [comment]
Ok then, I've reclassified this as a bug.

**Comment by wbbarr** [comment]
I think I've fixed this and made a minor improvement to the footerPopup (as loading may not take 3500 seconds).  I'm deploying to test this, and we'll see how it goes.

**Comment by sichinumi** [comment]
Resolved as of commit dcb07d1cc4077f26e0b3ad890fd53b2e96574f17
