### ISSUE TITLE
Chat logs for 1/1/2013 are showing up in 1/2/2013

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#32]
I'm not sure whether this is a @connergdavis issue or a @sichinumi issue, but if you pull the logs for 1/1/2013 on dev, you'll see that they stop at 18:59:59, and the logs from 1/2/2013 start at 1/1/2013 19:00:00.  This appears to be a time zone issue somewhere.

**Comment by sichinumi** [comment]
This was due to a data integrity issue that has been fixed - old data has been wiped. However, I'm leaving this issue open until we collect enough historical data to test it ourselves.

**Comment by wbbarr** [comment]
Resolved as of commit 0843f3a50d9b9b5878f2346a5af3cf9122db3a8a
