### ISSUE TITLE
Investigate way to Unit Test ValuesController (And possibly other controller) methods

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#38]
We need some way to unit test these methods.  We currently have a problem with using Moq to mock the GlobalStaticVars Static Core instance.  What do we need to do (either reengineering or just changes the way we test) to be able to write Unit Tests against Values Controller?

**Comment by EnzoMartin** [comment]
Not sure this is really a frontend issue..

**Comment by mamidon** [comment]
The code in question is frontend, but the work is infrastructure...

**Comment by wbbarr** [comment]
Do we have code pushed for this yet?

**Comment by EnzoMartin** [comment]
Will the frontend refactor affect this?

You can see current progress here:
https://github.com/EnzoMartin78/gswat/tree/frontend-refactor

**Comment by wbbarr** [comment]
I'm going to depri this down to p3.

**Comment by wbbarr** [comment]
Irrelevant as we just switched to ServiceStack.  We'll need to look into refactoring that to be IOC-friendly.
