### ISSUE TITLE
Settings menu displaces page contents awkwardly

### ISSUE THREAD

**Issue by sichinumi** [Pure-Battlefield/gswat#40]
Our quick-and-dirty solution for the settings menu is no longer good enough. It displaces the other contents of the page whenever it appears. It needs to either appear over the top of the other page contents, or go in a separate page of its own.

**Comment by connerdavis47** [comment]
Yeah I thought about this before, I'll try and see if there's some quick CSS hacks I can do to make it float peacefully.  Thanks for reminding me.

**Comment by EnzoMartin** [comment]
I can handle this as part of  Issue #43

**Comment by connerdavis47** [comment]
DO NOT PUSH ANYTHING FOR THIS

I've already patched it in Alvin's repo, he just needs to push it to main. ~~

**Comment by wbbarr** [comment]
Resolved as irrelevant due to frontend rework.
