### ISSUE TITLE
Server currently gives no feedback on unsuccessful connect and does not show connection info

### ISSUE THREAD

**Issue by ghost** [Pure-Battlefield/gswat#45]
If the app fails to connect to the server or indeed is connected (except by inspecting the HTTPResponse), there is no feedback to let the user know. Also, the only way to find out what server you are currently connected to is by checking the Azure StorageTable for the last server info.

Maybe it would be a good idea to write a few API methods that query the Azure storage for the Server IP and Port and write some custom error/success messages depending on the HTTPResponseMessage being returned by the Server.Connect method?

If we return the status message as a JSON string Enzo can easily bring it to the user in the front-end.

**Comment by ghost** [comment]
Added/prepared some of the above
https://github.com/behati/gswat/commit/000559c96e56bf92194d97f0dc8769d93e3382d2

**Comment by EnzoMartin** [comment]
We should start documenting some of these status/response messages

**Comment by ghost** [comment]
Agreed, we should create some dedicated Errorcodes/Statuscodes that we can pass along and write a short documentation on them :) I'll get to that. :+1:

**Comment by EnzoMartin** [comment]
Sounds good, add it to the wiki: https://github.com/Pure-Battlefield/gswat/wiki

**Comment by EnzoMartin** [comment]
So.. that documentation..

**Comment by ghost** [comment]
Implemented as part of #59
