### ISSUE TITLE
Absurdly high bandwidth usage

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#58]
1 user will use 70 gb a month. This is far too high.

**Comment by ghost** [comment]
That's loads! Is this from the chat-packages alone?

**Comment by wbbarr** [comment]
For the most part.  The only bandwidth Azure counts is outgoing bandwidth, so the info coming in from servers isn't counted.  

We have a fix in the works; @sichinumi and @EnzoMartin78 are going to be using timestamps to restrict what gets returned.
