### ISSUE TITLE
Migrate RCON credentials to Table Store

### ISSUE THREAD

**Issue by wbbarr** [Pure-Battlefield/gswat#9]
There are currently settings files sprinkled all over the project (3 to be exact) that have the RCON credentials in them.  It would be smarter to store these kinds of configuration options in a settings page on the web frontend that permits administrators to modify the RCON connection information and store those settings in Table Store.

Access to that page should be protected by a simple password (i.e. a user should be required to enter a password in order to access that page).

**Comment by sichinumi** [comment]
Conner is currently working on this. No other commits should occur until this page has been created and the settings files have been purged. I will be responsible for committing the final clean/purged repo as well as the settings page integration.

**Comment by wbbarr** [comment]
Any update on this?  I think I saw that the creds have been scrubbed from the settings files.

**Comment by sichinumi** [comment]
Server settings are currently configured using a settings menu on the main page - creds have indeed been scrubbed from settings files. It is now no longer possible to connect to "default" servers, you must always specify connection settings. Server settings have not yet been persisted in Table Store, pending some architectural decisions.

**Comment by sichinumi** [comment]
Resolved as of commit 58b78872daeb8a1688ab7060cb12aa79880ed2a3
